spring.application.name=subscriptionManager

spring.datasource.url=jdbc:mysql://localhost:3306/subscription_db
spring.datasource.username=root
spring.datasource.password=JulyDec728#1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
